# Generated by Django 4.2.10 on 2024-08-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_balance_balance_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='group_id',
            new_name='course_id',
        ),
    ]
