# Generated by Django 4.2.10 on 2024-08-19 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_group_id_subscription_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
