# Generated by Django 4.2.10 on 2024-08-16 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price_lesson_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='course_id',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
            preserve_default=False,
        ),
    ]
